name: test

on:
  push:
    branches: [main, dev]
  workflow_dispatch: ~
  
jobs:
  buildAndTest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: get branch
      run: |
        # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
        TAG=${GITHUB_REF##*/}
        if [ "$TAG" == "main" ] ; then TAG=latest ; fi
        echo "TAG=$TAG" >> $GITHUB_ENV
    - name: build
      run: docker build -t acdhch/aksearch-solr:$TAG --label "buildUrl=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" .
    - name: prepare data
      run: gunzip .github/workflows/marc.xml.gz
    - name: run
      run: |
        docker run --name aksearch-solr -d -p 8983:8983 -v "$PWD/.github/workflows/marc.xml:/marc/marc.xml" acdhch/aksearch-solr:$TAG
        sleep 5
        curl -i -I http://127.0.0.1:8983/solr/
    - name: import
      run: docker exec -t aksearch-solr bash -c 'cd /opt/aksearch && ./import-marc.sh /marc/marc.xml'
    - name: batch-import
      run: docker exec -t aksearch-solr bash -c 'cd /opt/aksearch && harvest/batch-import-marc.sh -m -d -z /marc'
    - uses: docker/login-action@v1
      with:
        username: zozlak
        password: ${{ secrets.DOCKERHUBTOKEN }}
    - name: docker push
      run: docker push acdhch/aksearch-solr:$TAG
    - name: redeploy
      run: |
        NMSP=oeaw-resources-dev
        if [ "$TAG" == "main"] ; then
          NMSP=oeaw-resources
        fi
        curl -X POST -H "Authorization: Bearer ${{ secrets.RANCHER_TOKEN }}" "https://rancher.acdh-dev.oeaw.ac.at/v3/project/c-zdbh8:p-dw4vh/workload/deployment:$NMSP:solr?action=redeploy"
